services:
  web:
    container_name: {{PROJECT_NAME}}_web
    image: {{PROJECT_NAME}}_web_image
    build: .
    ports:
      - "{{WEB_PORT}}:80"
      - "{{SSL_PORT}}:443"
    volumes:
      - ./:/var/www/html
      - ./certs/localhost.pem:/etc/ssl/certs/localhost.pem:ro
      - ./certs/localhost-key.pem:/etc/ssl/private/localhost-key.pem:ro
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME={{PROJECT_NAME}}
      - DB_USER=admin
      - DB_PASSWORD={{DB_PASSWORD}}
  db:
    container_name: {{PROJECT_NAME}}_db
    image: mysql:8.0
    command: --default-authentication-plugin=caching_sha2_password
    environment:
      MYSQL_ROOT_PASSWORD: {{DB_PASSWORD}}
      MYSQL_DATABASE: {{PROJECT_NAME}}
      MYSQL_USER: admin
      MYSQL_PASSWORD: {{DB_PASSWORD}}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "{{DB_PORT}}:3306"

volumes:
  mysql_data:
